artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://cdn.stackoverflow.co/files/jo7n4k8s/production/49915bfd46d0902c3564fd9a06b509d08a20488c.zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion


data_validation:
  root_dir: artifacts/data_validation
  unzip_data_dir: artifacts/data_ingestion/survey_results_public.csv
  STATUS_FILE: artifacts/data_validation/status.txt
  preprocessed_data_csv: artifacts/data_validation/preprocessed_data.csv 


data_transformation:
  root_dir: artifacts/data_transformation
  data_path: artifacts/data_validation/preprocessed_data.csv  


model_trainer:
  root_dir: artifacts/model_trainer
  train_data_path: artifacts/data_transformation/train.csv
  test_data_path: artifacts/data_transformation/test.csv
  model_name: model.joblib
  preprocessor: preprocessor.joblib